resilience4j.circuitbreaker:
  instances:
    customerService:
      failureRateThreshold: 50
      ringBufferSizeInClosedState: 5
      ringBufferSizeInHalfOpenState: 3
      waitDurationInOpenState: 20s
      automaticTransitionFromOpenToHalfOpenEnabled: true



#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/sim_activation
#    driverClassName: com.mysql.cj.jdbc.Driver
#    username: root
#    password: pass
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
